//IIFE ARE IMMEDIATELY INVOKED FUNCTION EXPRESSIONS THAT ARE USED , AS SOMETIMES THERE CAN BE POLLUTION FROM THE GLOBAL SCOPE HENCE TO REMOVE THAT POLLUTION OF THE VARIABLES FROM GLOBAL SCOPE WE USE IFFE

(function hello(){
    console.log("hello");
})();

//can work for arrow functions too
((name)=>{//PASSES THE NAME AS THE PARAMETER AND IN THE END YOU ARE PASSING THE ARGUMENT 
    console.log(`THIS IS SOMETHING NEW I LEARNED TODAY ON 05/08/24 ${name}`);
})('RITVIK BHATNAGAR');